### ISSUE TITLE
没太搞懂怎么用

### ISSUE THREAD

**Issue by murasame-chan** [lxl66566/ecust-electricity-statistics#2]
偶然发现的这个项目，但是我没学过编程，按照操作做了一遍发现没反应，让ai读了下代码发现：

> 这段代码并没有包含自动生成"data.js"文件的部分。它假设"data.js"文件已经存在，并尝试从中读取数据。如果文件不存在，它会忽略FileNotFoundError错误，并继续执行。

那如果是这样的话，第三步删除data.js后，程序不会自动生成新的data.js啊，页面也就无法显示了

但是我又只清空了data里面的数据，再次运行，并没有更新数据，虽然ai说：

> 是的，这段代码会往"data.js"文件中写入数据。具体来说，它会把每天的电力剩余量作为一个新的数据点添加到"data.js"文件中。这个数据点是一个包含时间和电力剩余量的字典，例如{"time": date, "kWh": remain}。
> 如果当前日期的数据已经存在（也就是说，今天已经有一个数据点了），那么它会更新这个数据点的电力剩余量。否则，它会添加一个新的数据点。
> 最后，它会把更新后的数据写回到"data.js"文件中。

但是并没有更新，3.9的数据还是68.8……

**Comment by lxl66566** [comment]
> 程序不会自动生成新的data.js

程序会在每日大致 09:30 定时运行， 并且将记录的数据更新至 `data.js`。若该文件不存在，则会自动创建。因此你需要删除 `data.js` 后，等到明天合适的时间再查看电费记录。（所以教程里有一句 [`请确保您已获取到电量数据`](https://github.com/lxl66566/ecust-electricity-statistics/blob/f9a39dba925939e6872a924c5fad388877afce0e/README.md?plain=1#L48)）

然后为什么要删除 `data.js`：因为里面的内容是我自己宿舍的电费数据，对其他人无用。

当然，如果你不想等到明天，你也可以手动运行程序：

![image](https://github.com/lxl66566/ecust-electricity-statistics/assets/88281489/a3600c9c-8f43-485a-9848-bd04d2e34b14)

然后理论上就能看到 `data.js` 中的更新了。

**Comment by murasame-chan** [comment]
感谢回复，按照操作已经调好了，已star
